# Generated by Django 2.2.4 on 2020-08-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managetemplate', '0006_variablecondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablecondition',
            name='project_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
