# Generated by Django 2.2.4 on 2020-08-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managetemplate', '0007_variablecondition_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablecondition',
            name='condition_content',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
