# Generated by Django 2.2.4 on 2020-08-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managetemplate', '0008_variablecondition_condition_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablecondition',
            name='variable_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
