# Generated by Django 2.2.4 on 2020-09-17 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managetemplate', '0012_permutationgeneral_permutation_rule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permutationparagraphs',
            old_name='paragraph_type',
            new_name='permutation_mode',
        ),
        migrations.RenameField(
            model_name='permutationparagraphs',
            old_name='max_ele_to_keep',
            new_name='rand_from',
        ),
        migrations.RenameField(
            model_name='permutationparagraphs',
            old_name='min_ele_to_keep',
            new_name='rand_to',
        ),
        migrations.RenameField(
            model_name='permutationparagraphs',
            old_name='permutation_rule',
            new_name='type',
        ),
    ]
