# Generated by Django 2.2.4 on 2020-09-17 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managetemplate', '0013_auto_20200917_0551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permutationgeneral',
            old_name='max_ele_to_keep',
            new_name='rand_from',
        ),
        migrations.RenameField(
            model_name='permutationgeneral',
            old_name='min_ele_to_keep',
            new_name='rand_to',
        ),
    ]
