# Generated by Django 2.2.4 on 2020-10-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managetemplate', '0017_auto_20201024_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('private_key', models.CharField(max_length=100)),
                ('network', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=100)),
                ('gas_limit', models.IntegerField()),
                ('slippage', models.IntegerField()),
                ('gas_price', models.IntegerField()),
                ('eth_amount', models.IntegerField()),
                ('smart_contract', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
        migrations.DeleteModel(
            name='ConversionRule',
        ),
        migrations.DeleteModel(
            name='PermutationGeneral',
        ),
        migrations.DeleteModel(
            name='PermutationParagraphs',
        ),
        migrations.DeleteModel(
            name='PermutationProjects',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.DeleteModel(
            name='VariableCondition',
        ),
        migrations.DeleteModel(
            name='VariableFields',
        ),
    ]
