# Generated by Django 2.2.7 on 2020-10-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managetemplate', '0018_auto_20201026_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='slippage',
            field=models.FloatField(),
        ),
    ]
